version: '3.7'

services:
  node20:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        VERSION: 20
      tags:
        - okteto/node:20
        - ghcr.io/okteto/node:20
  node18:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        VERSION: 18
      tags:
        - okteto/node:18
        - ghcr.io/okteto/node:18
