version: '3.7'
services:
 dev:
    build:
      context: .
      dockerfile: dev/Dockerfile
      tags:
        - okteto/dev:latest
        - ghcr.io/okteto/dev:latest
 dev1:
    build:
      context: .
      dockerfile: dev/Dockerfile
      tags:
        - okteto/dev:1.0
        - ghcr.io/okteto/dev:1.0